services:

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

  mysql-local:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: cliente
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  postgres-local:
    image: postgres:16
    container_name: postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oracle123
      POSTGRES_DB: ventas
    ports:
      - "5433:5432"

  oracle-local:
    image: gvenzl/oracle-free:latest
    container_name: oracle-local
    environment:
      ORACLE_PASSWORD: oracle123
      APP_USER: producto
      APP_USER_PASSWORD: 123
    ports:
      - "1522:1521"

  ms-producto:
    build: ./ms.producto
    container_name: ms-producto
    environment:
      TZ: America/Lima
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Lima
    ports:
      - "8080:8080"
    volumes:
      - ./central-config:/app/central-config
    depends_on:
      - oracle-local
      - consul

  ms-producto-2:
    build: ./ms.producto
    container_name: ms-producto-2
    environment:
      TZ: America/Lima
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Lima
      PRODUCTO_DATOS_INICIALES_ENABLED: "false"
    ports:
      - "8085:8080"
    volumes:
      - ./central-config:/app/central-config
    depends_on:
      - oracle-local
      - consul

  ms-cliente:
    build: ./ms.cliente
    container_name: ms-cliente
    environment:
      TZ: America/Lima
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Lima
    ports:
      - "8082:8082"
    volumes:
      - ./central-config:/app/central-config
    depends_on:
      - mysql-local
      - consul

  ms-auth:
    build: ./ms.auth
    container_name: ms-auth
    environment:
      TZ: America/Lima
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Lima
    ports:
      - "8084:8084"
    volumes:
      - ./central-config:/app/central-config
    depends_on:
      - mysql-local
      - consul

  ms-ventas:
    build: ./ms.ventas
    container_name: ms-ventas
    environment:
      TZ: America/Lima
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Lima
    ports:
      - "8083:8083"
    volumes:
      - ./central-config:/app/central-config
    depends_on:
      - postgres-local
      - ms-producto
      - ms-cliente
      - consul

  api-gateway:
    build: ./api.gateway
    container_name: api-gateway
    environment:
      TZ: America/Lima
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Lima
    ports:
      - "8030:8030"
    depends_on:
      - consul
      - ms-producto
      - ms-producto-2
      - ms-cliente
      - ms-auth
      - ms-ventas

  consul-registrator:
    image: curlimages/curl:latest
    container_name: consul-registrator
    depends_on:
      - consul
      - ms-producto
      - ms-producto-2
      - ms-cliente
      - ms-auth
      - ms-ventas
    entrypoint: >
      sh -c "
      sleep 40 &&

      curl -X PUT http://consul:8500/v1/agent/service/register
      -H 'Content-Type: application/json'
      -d '{\"Name\":\"ms-producto\",\"ID\":\"ms-producto-1\",\"Address\":\"ms-producto\",\"Port\":8080,\"Check\":{\"HTTP\":\"http://ms-producto:8080/q/health\",\"Interval\":\"10s\"}}' &&

      curl -X PUT http://consul:8500/v1/agent/service/register
      -H 'Content-Type: application/json'
      -d '{\"Name\":\"ms-producto\",\"ID\":\"ms-producto-2\",\"Address\":\"ms-producto-2\",\"Port\":8080,\"Check\":{\"HTTP\":\"http://ms-producto-2:8080/q/health\",\"Interval\":\"10s\"}}' &&

      curl -X PUT http://consul:8500/v1/agent/service/register
      -H 'Content-Type: application/json'
      -d '{\"Name\":\"ms-cliente\",\"ID\":\"ms-cliente-1\",\"Address\":\"ms-cliente\",\"Port\":8082,\"Check\":{\"HTTP\":\"http://ms-cliente:8082/q/health\",\"Interval\":\"10s\"}}' &&

      curl -X PUT http://consul:8500/v1/agent/service/register
      -H 'Content-Type: application/json'
      -d '{\"Name\":\"ms-auth\",\"ID\":\"ms-auth-1\",\"Address\":\"ms-auth\",\"Port\":8084,\"Check\":{\"HTTP\":\"http://ms-auth:8084/q/health\",\"Interval\":\"10s\"}}' &&

      curl -X PUT http://consul:8500/v1/agent/service/register
      -H 'Content-Type: application/json'
      -d '{\"Name\":\"ms-ventas\",\"ID\":\"ms-ventas-1\",\"Address\":\"ms-ventas\",\"Port\":8083,\"Check\":{\"HTTP\":\"http://ms-ventas:8083/q/health\",\"Interval\":\"10s\"}}' &&

      echo 'Servicios registrados en Consul correctamente'
      "
